name: Testing

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  windows-testing:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install swig
        run: |
          choco install python --version=3.8.0
          choco install --yes swig
      - name: Build
        run: make all
      - name: Run Tests
        run: |
          make all ;
          python -c "from pwnlib.tubes import process; process.send()"
      - name: Clean
        run: make clean
        
  ubuntu-testing:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install swig
        run: |
          sudo apt install --yes swig
      - name: Build
        run: echo "hello world"