name: Testing

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  windows-testing:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      
      - name: Install dependencies
        run: |
          choco install --yes swig
          choco install --yes doxygen.install
          choco install --yes doxygen.portable
          choco install --yes visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional" #choco install --yes visualstudio2022community --package-parameters "--allWorkloads --includeRecommended --includeOptional"
          choco install --yes windows-sdk-10.0 windowsdriverkit10
      - name: Install catch2
        run: |
          git clone https://github.com/catchorg/Catch2
          cd Catch2 ; mkdir build ; cd build 
          cmake -G "Visual Studio 17 2022" ..
          cmake --build . --target install
          cd ..
      - name: Build
        run: |
          make all PYENV=C:\hostedtoolcache\windows\Python\3.8.10\x64
      - name: Generate doxygen documentation
        run: |
          doxygen .\Doxyfile -w html
      - name: run C catch2 doctests
        run: |
          cd testing
          mkdir build && cd build
          cmake ..
          cmake --build .
          .\Debug\custom-main-tests.exe
      - name: Run Binding Tests
        run: |
          make all PYENV=C:\hostedtoolcache\windows\Python\3.8.10\x64
          python -c "from pwnlib.tubes import process; process.send()"
      - name: Clean 
        run: make clean
        
  ubuntu-testing:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install swig
        run: |
          sudo apt install --yes swig
      - name: Build
        run: echo "hello world"